const {MONGODB_URI, PORT, JWT_SECRET, TWILIO_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE, TERMII_SENDER, TERMII_API_KEY, CLOUDINARY_API_KEY, CLOUDINARY_SECRET_KEY, CLOUDINARY_CLOUD_NAME} = process.env


module.exports = {MONGODB_URI, PORT, JWT_SECRET, TWILIO_AUTH_TOKEN, TWILIO_SID, TWILIO_PHONE, TERMII_SENDER, TERMII_API_KEY, CLOUDINARY_API_KEY, CLOUDINARY_SECRET_KEY, CLOUDINARY_CLOUD_NAME}